### ISSUE TITLE
extraKeys属性设置无效

### ISSUE THREAD

**Issue by Cassie918** [cnu4/vue-codemirror-lite#18]
我把extraKeys: {"Ctrl": "autocomplete"}放进options对象，然后把整个使用codemirror组件封装成了一个组件在其他html页面中调用，options当中的其他属性都能有效果，唯独extraKeys属性无效。

**Comment by cnu4** [comment]
看一下这里的 [demo](https://cnu4.github.io/vue-codemirror-lite/)

可能是你设置的快捷键与系统的快捷键冲突了，试试 `Alt-Space` 或其他组合
