### ISSUE TITLE
how can i use placeholder ?

### ISSUE THREAD

**Issue by idonteatcookie** [cnu4/vue-codemirror-lite#19]
I tried the following two methods are not effective…
```
<template>
  <codemirror placeholder="zzz" :options="options"></codemirror>
</template>

<script>
  export default {
    data () {
      return {
        options: {
          placeholder: 'zzz'
        }
      }
    }
  }
</script>
```

**Comment by cnu4** [comment]
By default (to optimise bundle size) all modes and addons are not included. For using addons in component, see [here](https://github.com/cnu4/vue-codemirror-lite#using-language-modes-and-addons).

You need to include addon `placeholder`. View a browser demo [here](https://jsfiddle.net/Lx7cur5f/1/)

For CodeMirror `placeholder` usage, see [here](https://codemirror.net/doc/manual.html#addon_placeholder).

**Comment by idonteatcookie** [comment]
thanks. I add the following code and it working.
 ```
import 'codemirror/addon/display/placeholder.js'
 .CodeMirror pre.CodeMirror-placeholder { color: #999; }
```
