### ISSUE TITLE
How can I change the theme?

### ISSUE THREAD

**Issue by chrzrdx** [cnu4/vue-codemirror-lite#2]
I'm trying to import the theme css as such:
```
<style lang="stylus">
import 'codemirror/theme/3024-night.css'
</style>
```

and using it in the options I pass to the codemirror component as:
```
options: {
  theme: '3024-night'
}
```
But the theme doesn't get applied.

I'm using the default vue-cli webpack template.

**Comment by chrzrdx** [comment]
Currently loading the theme file from external CDN makes it work. Is there a way/benefit to doing it with import syntax?

**Comment by cnu4** [comment]
Just like [using language modes and addons](https://github.com/cnu4/vue-codemirror-lite#using-language-modes-and-addons), you can change the theme like this

```vue
<template>
  <codemirror :options="options"></codemirror>
</template>

<script>
  import 'codemirror/theme/3024-night.css'

  export default {
    data () {
      return {
        options: {
          theme: '3024-night'
        }
      }
    }
  }
</script>
``` 

Import css file in `<script>` block.

In addition, you are missing a quote mark in the @import line inside `<style>` block.
