### ISSUE TITLE
编辑器光标有时会定位不准，如果在第一行时，不显示光标

### ISSUE THREAD

**Issue by QiuYX1994** [cnu4/vue-codemirror-lite#21]
编辑器光标有时会定位不准，如果定位在第一行时，不显示光标
![image](https://user-images.githubusercontent.com/37650775/54186166-b9634100-44e5-11e9-803c-6eb1557d4e41.png)，这个是什么问题导致的

**Comment by cnu4** [comment]
具体是使用 API 来定位在第一行吗，定位在其他行就没问题吗

**Comment by QiuYX1994** [comment]
不是，就是点击的时候，我在同一个页面用了多个编辑器，有的不会

**Comment by QiuYX1994** [comment]
还有一个问题就是，它可以通过什么方法定位到最后一行

**Comment by QiuYX1994** [comment]
在谷歌浏览器上，在没有输入内容之前会出现首行光标高度为0，第二行光标 top值会比其他浏览器小1px，
![image](https://user-images.githubusercontent.com/37650775/54406631-c6667700-4715-11e9-9d85-2125d027582b.png)，输入内容之后，恢复正常
![image](https://user-images.githubusercontent.com/37650775/54406704-0d546c80-4716-11e9-9610-9da5dca62327.png) 小的这个1px，会导致之后的每行都定位不准

**Comment by cnu4** [comment]
这可能是 codemirror 本身的异常，建议到 codemirror issues 找一下解决办法

定位到最后一行的方法可以[在这里](https://codemirror.net/doc/manual.html#api_selection)看下 `doc.setCursor` API
