### ISSUE TITLE
Syncronising scroll with a preview Div scroll.

### ISSUE THREAD

**Issue by titpetric** [cnu4/vue-codemirror-lite#4]
Hello,

how would I go about synchronizing a scroll with another div element that contains the preview? With a textarea I can use @scroll=xxx on both elements, and synchronise them accordingly. With this component I'd likely need some way to access `this.editor` and watch scrollTo/getScrollInfo?

Any help is appreciated :)

**Comment by cnu4** [comment]
You can access editor object like this.

```vue
<!--template-->
<codemirror
  ref="myEditor">
</codemirror>
```

```js
// script
export default {
  computed: {
    editor() {
      // get current editor object
      return this.$refs.myEditor.editor
    }
  },
  mounted() {
    // use editor object...
    this.editor.focus()
    console.log('this is current editor object', this.editor)
  }
}
```

And register scroll event with the `on` methods on the editor objects.

```js
this.editor.on('scroll', function(cm) {
  // do something...
}
```

For more events, see [http://codemirror.net/doc/manual.html#events](http://codemirror.net/doc/manual.html#events)
