### ISSUE TITLE
Can't figure it out

### ISSUE THREAD

**Issue by Sjoerd** [cnu4/vue-codemirror-lite#6]
Hello,
I'm making my first (hello world) project in Vue, and want to use this package.
My bootstrap.js looks like this:
```import Vue from 'vue';
import VueRouter from 'vue-router';
import axios from 'axios';
import Form from './utilities/Form';
import { codemirror } from 'vue-codemirror-lite';

window.Vue = Vue;
Vue.use(VueRouter);

window.axios = axios;
window.axios.defaults.headers.common = {
	'X-Requested-With': 'XMLHttpRequest'
}
window.Form = Form;


export default {
  components: {
    codemirror
  }
}
```

and i'm getting the error "Unknown custom element: <codemirror> - did you register the component correctly? For recursive components, make sure to provide the "name" option.". Is this a bug, or do I do something wrong?

**Comment by cnu4** [comment]
Did other component that you imported work correctly?

And which file occurred this error? Maybe you could try register `codemirror ` in the `vue` file that `template` section used  `codemirror `.
