### ISSUE TITLE
How can I destroy it?

### ISSUE THREAD

**Issue by zhuanni** [cnu4/vue-codemirror-lite#7]
I use it in a route page of a vue project,but when leaving from the route page to another route page,the console would show the error:
TypeError: Cannot read property 'removeChild' of null
Is it because the instance is not destroyed?
I would be very grateful if you could help.

**Comment by cnu4** [comment]
The `codemirror ` instance will be destroyed when the component was unmounted.

Could you please post the detail of the error?

**Comment by zhuanni** [comment]
There are three tabs on the page,when one tab is show,the other two tabs are hide.
The error would show beacuse of the codemirrors in hide tabs when leaving the page.
![aaa](https://user-images.githubusercontent.com/15973722/30416540-2731ab7e-995f-11e7-8831-9c8980b1379e.jpg)

**Comment by cnu4** [comment]
Did you use `v-if` to hide tabs? Maybe you can try `v-show`.

Could you provide a small reproduction of the problem as it appears to you. you can provide it in [jsfiddle](https://jsfiddle.net/).
